name: pyomadb-examples-environment
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - pip:
    - omadb
    - goatools
    - dendropy
    - ete3
